before_script:
  - export RUST_BACKTRACE=1
  - echo $JAVA_HOME
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
jdk:
  - oraclejdk8
language: rust
matrix:
  allow_failures:
    - rust: nightly
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  # TODO: find out where `libjvm` is on Travis.
  #- osx
