[package]
authors = ["Lennart Kudling"]
build = "build.rs"
description = "Calling Java code from Rust via JNI"
keywords = ["java", "jni"]
license = "MIT/Apache-2.0"
links = "jvm"
name = "rucaja"
readme = "README.md"
version = "0.1.0"

[dependencies]
jni-sys="0.2.1"
